### ISSUE TITLE
Add more log when auth failed

### ISSUE THREAD

**Issue by chnliyong** [juicedata/juicefs-csi-driver#57]
Add more log when auth failed, like the output returned by auth process.

**Comment by chnliyong** [comment]
The `stdout` and `stderr` have already logged, ref [code](https://github.com/juicedata/juicefs-csi-driver/blob/59486560a35cc81fe823c5e01b6b6f27e2a410c2/pkg/juicefs/juicefs.go#L117), I reproduced in my local develop environment and below is the log from  _command_ `kubectl -n kube-system logs -f juicefs-csi-node-bpbgr -c juicefs-plugin` where `juicefs-csi-node-bpbgr` is my local JuiceFS node pod ID:
```
I1027 07:14:23.537452       1 juicefs.go:117] MountFs: authentication output is 'Invalid name or token: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/bin/juicefs", line 2220, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/juicefs", line 2218, in main
    return globals()[command]()
  File "/usr/bin/juicefs", line 915, in auth
    passphrase=options.passphrase)
  File "/usr/bin/juicefs", line 724, in load_cfg
    return update_cfg(name, timeout, **cfg)
  File "/usr/bin/juicefs", line 776, in update_cfg
    storage = cfg['storage']
KeyError: 'storage'
'
```

Close this issue.
