### ISSUE TITLE
e2e flaky test

### ISSUE THREAD

**Issue by zxh326** [juicedata/juicefs-csi-driver#866]
log

```sh

2024-01-30 05:59:02,615 Get csi controller log:
2024-01-30 05:59:02,633 I0130 05:52:28.355365       1 main.go:92] Run CSI controller
I0130 05:52:28.355613       1 driver.go:50] Driver: csi.juicefs.com version efc716c commit efc716c37cd88323774961e08b7e639b7e525647 date 2024-01-30T05:49:03Z
I0130 05:52:28.374705       1 driver.go:115] Listening for connection on address: &net.UnixAddr{Name:"/var/lib/csi/sockets/pluginproxy/csi.sock", Net:"unix"}
I0130 05:52:29.579451       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:52:29.581148       1 identity.go:30] GetPluginInfo: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:52:29.582211       1 identity.go:41] GetPluginCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:52:29.583617       1 controller.go:157] ControllerGetCapabilities: called with args &csi.ControllerGetCapabilitiesRequest{XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
I0130 05:52:30.705388       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:52:30.706222       1 identity.go:30] GetPluginInfo: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:52:30.706622       1 identity.go:41] GetPluginCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:52:30.706948       1 controller.go:157] ControllerGetCapabilities: called with args &csi.ControllerGetCapabilitiesRequest{XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
I0130 05:52:30.775877       1 identity.go:30] GetPluginInfo: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:52:44.442304       1 controller.go:134] Volume pv-static-delete not dynamic PV, ignore.
I0130 05:52:47.960962       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:52:57.961607       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:53:07.961450       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:53:17.961115       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:53:27.961227       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:53:37.960822       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:53:47.961072       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:53:57.961512       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:54:07.961422       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:54:17.961823       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:54:27.961461       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:54:37.961348       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:54:47.961741       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:54:57.961188       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:55:07.961644       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:55:17.961448       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:55:27.961781       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:55:37.961169       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:55:47.961813       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:55:57.961895       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:56:07.961720       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:56:17.965533       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:56:27.961229       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:56:37.962150       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:56:47.961100       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:56:57.961449       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:57:07.961376       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:57:17.960887       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:57:27.961270       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:57:37.961223       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:57:47.961832       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:57:57.961555       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:58:07.961781       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:58:17.961075       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:58:27.961357       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:58:37.960979       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:58:43.995510       1 controller.go:74] CreateVolume: Secrets contains keys [token accesskey bucket name secretkey storage]
I0130 05:58:47.961405       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0130 05:58:57.960851       1 identity.go:59] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}

2024-01-30 05:59:02,633 Get event: 
E0130 05:59:03.017502   42888 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0130 05:59:03.018020   42888 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0130 05:59:03.019492   42888 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0130 05:59:03.019965   42888 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0130 05:59:03.021387   42888 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Traceback (most recent call last):
  File "/home/runner/work/juicefs-csi-driver/juicefs-csi-driver/.github/scripts/e2e-test.py", line 180, in <module>
    test_dynamic_cache_clean_upon_umount()
  File "/home/runner/work/juicefs-csi-driver/juicefs-csi-driver/.github/scripts/test_case.py", line 1000, in test_dynamic_cache_clean_upon_umount
    raise Exception("Cache empty")
Exception: Cache empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/juicefs-csi-driver/juicefs-csi-driver/.github/scripts/e2e-test.py", line 190, in <module>
    die(e)
  File "/home/runner/work/juicefs-csi-driver/juicefs-csi-driver/.github/scripts/util.py", line 49, in die
    subprocess.run(["sudo", "kubectl", "get", "event", "--all-namespaces"], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'kubectl', 'get', 'event', '--all-namespaces']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

cases:

- https://github.com/juicedata/juicefs-csi-driver/actions/runs/7739153705/job/21101427471

**Comment by zxh326** [comment]
It may be a disk space issue that was fixed in #870.

**Comment by zxh326** [comment]
https://github.com/juicedata/juicefs-csi-driver/actions/runs/8225816269/job/22491386096

upstream juicefs bug
